### ISSUE TITLE
Can't install on LC_Docker

### ISSUE THREAD

**Issue by IMAI-Yuji** [NII-cloud-operation/sshkernel#12]
## Expected

To install on [Jupyter-LC_docker](https://github.com/NII-cloud-operation/Jupyter-LC_docker)

## What happen instead

Menu did not appear at `New` -> `Notebook`

![image](https://user-images.githubusercontent.com/1840560/59013496-0f414e00-8875-11e9-8162-0158d9f39a23.png)

Kernel placed on CONDA_DIR.
```
jovyan@8ba5cd9809ae:~$ jupyter kernelspec list
Available kernels:
  bash               /opt/conda/share/jupyter/kernels/bash
  bash-wrapper       /opt/conda/share/jupyter/kernels/bash-wrapper
  python3            /opt/conda/share/jupyter/kernels/python3
  python3-wrapper    /opt/conda/share/jupyter/kernels/python3-wrapper
  ssh                /opt/conda/share/jupyter/kernels/ssh
```

## Step to reproduce

Build docker image as follows

```
FROM niicloudoperation/notebook:latest

USER root

RUN pip install -U sshkernel --proxy=http://user@proxy.example.com:port/
RUN python -m sshkernel install --prefix=/opt/conda

USER $NB_USER
```
- Container hash: sha256:68bafa4c4e623ae83d86a46e08e8f48aa948fa950ccc12feb3a6564d6e370436
- Commit on LC_Docker: https://github.com/NII-cloud-operation/Jupyter-LC_docker/tree/b3ecdc0158be2d0168c37eb1db2a05aa44507fd5

**Comment by m-ueno** [comment]
I'm closing this issue because this issue is about Jupyter-LC_docker and/or Jupyter-LC_wrapper, not about sshkernel.

Thank you anyway.

**Comment by IMAI-Yuji** [comment]
They made their images to prevent installing packages other than python3 and bash by https://github.com/NII-cloud-operation/Jupyter-LC_docker/pull/67 . I have confirmed that sshkernel work fine when reverting their PR.

I will talked with them how sshkernel install on their image. Thanks.
