### ISSUE TITLE
Installation stalls on a more recent version of metakernel

### ISSUE THREAD

**Issue by alexhrescale** [NII-cloud-operation/sshkernel#13]
Hello, thank you for this useful work. I have not yet been able to run this successfully. However, it looks like there is a compatibility regression in metakernel that causes the installation to stall.

Currently you declare `metakernel>=0.20.0` in https://github.com/NII-cloud-operation/sshkernel/blob/master/requirements.txt#L4. As of this comment, the latest version is `0.24.2`.

My test environment has
```
[nix-shell:~]$ pip list | grep 'ipykernel\|ipython'
ipykernel                         5.1.2
ipython                           7.7.0
```

On my system for any `metakernel>=0.22.1`, running `python -m sshkernel install --sys-prefix` will stall. The command is stuck, and does not do anything. This happens somewhere inside the `kernelapp.InteractiveShellApp` superclass call, which I did not dig further into.

```
[nix-shell:~]$ pip list | grep metakernel
metakernel                        0.22.1
[nix-shell:~]$ python -m sshkernel install --sys-prefix
# does not complete. Ctrl-C
```

After downgrading to `metakernel==0.22.0`, the installation completes:

```
[nix-shell:~]$ pip list | grep metakernel
metakernel                        0.22.0
[nix-shell:~]$ python -m sshkernel install --sys-prefix
[InstallKernelSpec] Removing existing kernelspec in /var/folders/q7/10108k191c5f_dktqjg0dqym0000gp/T/tmp.3MfnoiNxGe-venv/share/jupyter/kernels/ssh
[InstallKernelSpec] Installed kernelspec ssh in /var/folders/q7/10108k191c5f_dktqjg0dqym0000gp/T/tmp.3MfnoiNxGe-venv/share/jupyter/kernels/ssh
```

**Comment by alexhrescale** [comment]
If we must have `metakernel==0.24.2` AND must install the kernel, this actually successfully installs the kernel:

```
pip install metakernel==0.22.0
python -m sshkernel install
pip install metakernel==0.24.2
```

Whether the kernel operates correctly is a separate issue.

**Comment by m-ueno** [comment]
I confirmed the installation works in CI with recent Ubuntu (conda) and Debian (non-conda) container images (see also #14).
Sorry for stopping further investigation.
