### ISSUE TITLE
magic commands not registered

### ISSUE THREAD

**Issue by mcree** [NII-cloud-operation/sshkernel#23]
Hello,

Since version 0.9.2 the magic commands %login and %logout are not registered in jupyter (as in %lsmagic)

Tested with jupyter labs 1.2.x and 2.0.x. Version 0.9.2 works OK for both versions.

Regards,
Ernie

**Comment by m-ueno** [comment]
Hi @mcree, thanks for the feedback.

Hmmm, the test to run a notebook with login and logout wrote on it passed today without error. <https://gitlab.com/m-ueno/sshkernel/-/jobs/497036345>
Can you give us a little more information? Maybe the other libraries installed are outdated.
Can you try it out in a new environment?

**Comment by baflo** [comment]
+1

I have jupyterlab@2.1.1 running in a Docker Container based upon `jupyter/scipy-notebook` with sshkernel@0.10.0 and libssl@1.0.0

**Comment by baflo** [comment]
Apparently, from v0.9.2 to v0.9.3 you moved `magics` to an own directory, but this is not in the [package](https://files.pythonhosted.org/packages/86/ac/1f2874592350628146ed88476038a32976b56aaacda37a385173780d16c0/sshkernel-0.9.3.tar.gz)
