### ISSUE TITLE
%logout should revert to local bash

### ISSUE THREAD

**Issue by mjbright** [NII-cloud-operation/sshkernel#29]
Really pleased to discover this kernel which seems to work well.

For my use case I'd really like to have a bash notebook where we can

- run commands locally
- %login HOSTA, run commands on HOSTA, %logout
- run commands locally
- %login HOSTB, run commands on HOSTB, %logout
- run commands locally

I guess a merge of bash_kernel and sshkernel would do the (big) job ...

**Comment by m-ueno** [comment]
Thank you for sharing your use case.
Unfortunately, it is not feasible with the current architecture.

As alternatives:
* You can use explicit `!` magic to run commands locally.
* [SoS Polyglot Notebook](https://vatlab.github.io/sos-docs/) might work. (We have not confirmed that it works.)

Thank you for the good feedback.
